/* Process model C form file: bt_mst_lmp_src_sink.pr.c */
/* Portions of this file copyright 2014 by Riverbed Technology. All rights reserved. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from bt_mst_lmp_src_sink.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char bt_mst_lmp_src_sink_pr_c [] = "MIL_3_Tfile_Hdr_ 1800 30A modeler 7 554D6E92 554D6E92 1 rhel06 chaganti 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 468d 2                                                                                                                                                                                                                                                                                                                                                                                                          ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */

/***********************************************/
// The SuiteTooth model set was developed by
// HIGHLAND SYSTEMS, INC.
//
// It incorporates code available in the public
// domain and other code that is the property of
// OPNET Technologies, Inc.
//
// Inquiries may be addressed to:
// 
// Highland Systems, Inc.
// (703) 312 0830
// info@highsys.com
// www.highsys.com
/***********************************************/

/* Include files. */
#include "oms_dist_support.h"
#include <math.h>

/* Define constants used in the process model.	*/
//#define	OFF_TO_ON			10
//#define	ON_TO_ON			20
//#define	ON_TO_OFF			30


/* State transition macro definitions.	*/
//#define	REMAIN_ACTIVE		(intrpt_type == OPC_INTRPT_SELF && intrpt_code < 8)
#define	SELF_INT			(intrpt_type == OPC_INTRPT_SELF)
#define STRM_INT			(intrpt_type == OPC_INTRPT_STRM)

/* Function Declarations.	*/
static void			bt_source_sv_init ();

#define CONTROL 10

#define BT_TRACE_ACTIVE		(op_prg_odb_ltrace_active ("bluetooth"))


typedef struct
	{
	double start_time;
	double stop_time;
	OmsT_Dist_Handle int_arrival;
	OmsT_Dist_Handle pkt_size;
	int destination;
	}Control_Traffic;

/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
typedef struct
	{
	/* Internal state tracking for FSM */
	FSM_SYS_STATE
	/* State Variables */
	Stathandle	             		pksize_stathandle                               ;	/* Statistic handle to the "Packet Generation Status" statistic */
	Stathandle	             		bits_sent_stathandle                            ;
	Stathandle	             		bitssec_sent_stathandle                         ;
	Stathandle	             		pkts_sent_stathandle                            ;
	Stathandle	             		pktssec_sent_stathandle                         ;
	Stathandle	             		bits_sent_gstathandle                           ;
	Stathandle	             		bitssec_sent_gstathandle                        ;
	Stathandle	             		pkts_sent_gstathandle                           ;
	Stathandle	             		pktssec_sent_gstathandle                        ;
	int	                    		dest_addr                                       ;	/* destination address - slave, bcast, or random */
	double	                 		pkts_sent                                       ;
	int	                    		pk_num                                          ;
	Stathandle	             		pkts_sent_dimstathandle[7]                      ;
	double	                 		pk_sent_dim[7]                                  ;
	int	                    		Slave_addr                                      ;
	Control_Traffic	        		control_table[8]                                ;
	int	                    		num_control_connections                         ;
	Stathandle	             		bits_rcvd_stathandle                            ;
	Stathandle	             		bitssec_rcvd_stathandle                         ;
	Stathandle	             		pkts_rcvd_stathandle                            ;
	Stathandle	             		pktssec_rcvd_stathandle                         ;
	Stathandle	             		ete_delay_stathandle                            ;
	Stathandle	             		bits_rcvd_gstathandle                           ;
	Stathandle	             		bitssec_rcvd_gstathandle                        ;
	Stathandle	             		pkts_rcvd_gstathandle                           ;
	Stathandle	             		pktssec_rcvd_gstathandle                        ;
	Stathandle	             		ete_delay_gstathandle                           ;
	double	                 		pkts_rcvd                                       ;
	Stathandle	             		control_bitssec_rcvd_stathandle                 ;
	Stathandle	             		control_pkts_rcvd_stathandle                    ;
	Stathandle	             		control_ete_delay_stathandle                    ;
	double	                 		control_pkts_rcvd                               ;
	} bt_mst_lmp_src_sink_state;

#define pr_state_ptr            		((bt_mst_lmp_src_sink_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr))
#define pksize_stathandle       		pr_state_ptr->pksize_stathandle
#define bits_sent_stathandle    		pr_state_ptr->bits_sent_stathandle
#define bitssec_sent_stathandle 		pr_state_ptr->bitssec_sent_stathandle
#define pkts_sent_stathandle    		pr_state_ptr->pkts_sent_stathandle
#define pktssec_sent_stathandle 		pr_state_ptr->pktssec_sent_stathandle
#define bits_sent_gstathandle   		pr_state_ptr->bits_sent_gstathandle
#define bitssec_sent_gstathandle		pr_state_ptr->bitssec_sent_gstathandle
#define pkts_sent_gstathandle   		pr_state_ptr->pkts_sent_gstathandle
#define pktssec_sent_gstathandle		pr_state_ptr->pktssec_sent_gstathandle
#define dest_addr               		pr_state_ptr->dest_addr
#define pkts_sent               		pr_state_ptr->pkts_sent
#define pk_num                  		pr_state_ptr->pk_num
#define pkts_sent_dimstathandle 		pr_state_ptr->pkts_sent_dimstathandle
#define pk_sent_dim             		pr_state_ptr->pk_sent_dim
#define Slave_addr              		pr_state_ptr->Slave_addr
#define control_table           		pr_state_ptr->control_table
#define num_control_connections 		pr_state_ptr->num_control_connections
#define bits_rcvd_stathandle    		pr_state_ptr->bits_rcvd_stathandle
#define bitssec_rcvd_stathandle 		pr_state_ptr->bitssec_rcvd_stathandle
#define pkts_rcvd_stathandle    		pr_state_ptr->pkts_rcvd_stathandle
#define pktssec_rcvd_stathandle 		pr_state_ptr->pktssec_rcvd_stathandle
#define ete_delay_stathandle    		pr_state_ptr->ete_delay_stathandle
#define bits_rcvd_gstathandle   		pr_state_ptr->bits_rcvd_gstathandle
#define bitssec_rcvd_gstathandle		pr_state_ptr->bitssec_rcvd_gstathandle
#define pkts_rcvd_gstathandle   		pr_state_ptr->pkts_rcvd_gstathandle
#define pktssec_rcvd_gstathandle		pr_state_ptr->pktssec_rcvd_gstathandle
#define ete_delay_gstathandle   		pr_state_ptr->ete_delay_gstathandle
#define pkts_rcvd               		pr_state_ptr->pkts_rcvd
#define control_bitssec_rcvd_stathandle		pr_state_ptr->control_bitssec_rcvd_stathandle
#define control_pkts_rcvd_stathandle		pr_state_ptr->control_pkts_rcvd_stathandle
#define control_ete_delay_stathandle		pr_state_ptr->control_ete_delay_stathandle
#define control_pkts_rcvd       		pr_state_ptr->control_pkts_rcvd

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	bt_mst_lmp_src_sink_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((bt_mst_lmp_src_sink_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ + 2};
#endif

static void
bt_lmp_sv_init ()
	{
	Objid				my_id;
	char				intarrvl_rate_string [128], packet_size_string [128];
	char				start_time_string [128];
	char                control_start_time_string[128];
	OmsT_Dist_Handle	start_time_dist_handle;
	OmsT_Dist_Handle    control_start_time_dist_handle;
	int 				i, dest, slave_addr;
	int 				num_acl_rows, num_sco_rows, num_control_rows;
	
	Objid   control_traf_params;
	Objid   control_id[8];


	/**	Initializes state variables associated with		**/
	/**	this process model.								**/
	FIN (bt_lmp_sv_init ());

	/*	Determine the object ID.*/
	my_id = op_id_self ();

	pkts_sent = 0;
	num_control_rows = 0;

	/* Build tables of traffic parameters */
	
	/* First get the ids of the attribute sets */
	op_ima_obj_attr_get (my_id, "Master->Slave Control Traffic", &control_traf_params);


	num_control_rows = op_topo_child_count (control_traf_params, OPC_OBJTYPE_GENERIC);
	
	
	for (i=0; i<num_control_rows; i++)
		{
		/* Get  row objid */
		control_id[i] = op_topo_child (control_traf_params, OPC_OBJTYPE_GENERIC, i);
		
		/* Get the destination address		*/
		op_ima_obj_attr_get (control_id[i], "Destination Address", &dest);

		control_table[i].destination = dest;
		
		/* Get the start time */
		op_ima_obj_attr_get (control_id[i], "Start Time", start_time_string);
		
		if (strcmp (start_time_string, "Never") != 0)
			{
			start_time_dist_handle = oms_dist_load_from_string (start_time_string);
			control_table[i].start_time = oms_dist_outcome (start_time_dist_handle);
			}
		else
			{
			control_table[i].start_time = -1.0;
			}

		/* If there will be traffic to this destination, find out what type	*/ 
		if (control_table[i].start_time >= 0.0)
			{
			/* Determine the stop time for data traffic generation.	*/
			op_ima_obj_attr_get (control_id[i], "Stop Time", &control_table[i].stop_time);
			if (control_table[i].stop_time == -1.0)
				control_table[i].stop_time = OPC_DBL_INFINITY;
			}
			
		if (control_table[i].stop_time > control_table[i].start_time)
			{
			/* Load the distributions used to determine packet generation */

			op_ima_obj_attr_get (control_id[i], "Interarrival Time", intarrvl_rate_string);
			control_table[i].int_arrival = oms_dist_load_from_string (intarrvl_rate_string);
			op_ima_obj_attr_get (control_id[i], "Packet Size", packet_size_string);
			control_table[i].pkt_size =  oms_dist_load_from_string (packet_size_string);
			}
				 
		}/* End control attributes */

	for (i=0; i<7; i++)
		{
		/* initialize dimensioned packet count */
		pk_sent_dim[i] = 0;
		}


		/*	Initialize the packet generation status statistic	*/
		/*	to indicate that currently there are no packets 	*/
		/*	being generated.									*/
		pksize_stathandle = op_stat_reg ("Control.Packet Generation Status", OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
		op_stat_write (pksize_stathandle, (double) OPC_FALSE);
		
		/* Initilaize the statistic handles to keep	*/
		/* track of traffic Sourceed by this process.	*/
		bits_sent_stathandle 		= op_stat_reg ("Control.Traffic Sent (bits)",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
		bitssec_sent_stathandle 	= op_stat_reg ("Control.Traffic Sent (bits/sec)",	OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
		pkts_sent_stathandle 		= op_stat_reg ("Control.Traffic Sent (packets)",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
		pktssec_sent_stathandle 	= op_stat_reg ("Control.Traffic Sent (packets/sec)",	OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);

		bits_sent_gstathandle 		= op_stat_reg ("Control.Traffic Sent (bits)",		OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);
		bitssec_sent_gstathandle 	= op_stat_reg ("Control.Traffic Sent (bits/sec)",	OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);
		pkts_sent_gstathandle 		= op_stat_reg ("Control.Traffic Sent (packets)",		OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);
		pktssec_sent_gstathandle 	= op_stat_reg ("Control.Traffic Sent (packets/sec)",	OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);

	    for (slave_addr=0; slave_addr<7; slave_addr++)
			pkts_sent_dimstathandle[slave_addr] 	= op_stat_reg ("Control.Traffic by Slave (packets)",	slave_addr, OPC_STAT_LOCAL);
		
		num_control_connections = num_control_rows;

	FOUT;
	}

/* End of Function Block */

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

#if defined (__cplusplus)
extern "C" {
#endif
	void bt_mst_lmp_src_sink (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Obtype _op_bt_mst_lmp_src_sink_init (int * init_block_ptr);
	void _op_bt_mst_lmp_src_sink_diag (OP_SIM_CONTEXT_ARG_OPT);
	void _op_bt_mst_lmp_src_sink_terminate (OP_SIM_CONTEXT_ARG_OPT);
	VosT_Address _op_bt_mst_lmp_src_sink_alloc (VosT_Obtype, int);
	void _op_bt_mst_lmp_src_sink_svar (void *, const char *, void **);


#if defined (__cplusplus)
} /* end of 'extern "C"' */
#endif




/* Process model interrupt handling procedure */


void
bt_mst_lmp_src_sink (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (bt_mst_lmp_src_sink ());

		{
		/* Temporary Variables */
		int					intrpt_type;
		int					intrpt_code;
		
		Packet*				pkptr;
		int					pksize;
		double				dval0 = 0.0;
		double				dval1 = 0.0;
		double				next_packet_arrival_time;
		Boolean 			send_pkt;
		
		Ici*	bt_ici;
		int i, slave_addr;
		
		char str0[128], str1[32];
		double		pk_size;
		double		ete_delay;
		int intrpt_stream;
		/* End of Temporary Variables */


		FSM_ENTER ("bt_mst_lmp_src_sink")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (init) enter executives **/
			FSM_STATE_ENTER_FORCED_NOLABEL (0, "init", "bt_mst_lmp_src_sink [init enter execs]")
				FSM_PROFILE_SECTION_IN ("bt_mst_lmp_src_sink [init enter execs]", state0_enter_exec)
				{
				/* Initilaize the statistic handles to keep	*/
				/* track of traffic sinked by this process.	*/
				bits_rcvd_stathandle 		= op_stat_reg ("Control.Traffic Received (bits)",			OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				bitssec_rcvd_stathandle 	= op_stat_reg ("Control.Traffic Received (bits/sec)",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				pkts_rcvd_stathandle 		= op_stat_reg ("Control.Traffic Received (packets)",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				pktssec_rcvd_stathandle 	= op_stat_reg ("Control.Traffic Received (packets/sec)",	OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				ete_delay_stathandle		= op_stat_reg ("Control.End-to-End Delay (seconds)",		OPC_STAT_INDEX_NONE, OPC_STAT_LOCAL);
				
				bits_rcvd_gstathandle 		= op_stat_reg ("Control.Traffic Received (bits)",			OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);
				bitssec_rcvd_gstathandle 	= op_stat_reg ("Control.Traffic Received (bits/sec)",		OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);
				pkts_rcvd_gstathandle 		= op_stat_reg ("Control.Traffic Received (packets)",		OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);
				pktssec_rcvd_gstathandle 	= op_stat_reg ("Control.Traffic Received (packets/sec)",	OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);
				ete_delay_gstathandle		= op_stat_reg ("Control.End-to-End Delay (seconds)",		OPC_STAT_INDEX_NONE, OPC_STAT_GLOBAL);
				pkts_rcvd = 0;
				control_pkts_rcvd = 0.0;
				/* Initialize the traffic generation parameters.	*/
				bt_lmp_sv_init ();
				
				/* Schedule the first self-interrupt for each connection */
				for(i=0;i<num_control_connections;i++)
					{
						if (control_table[i].start_time >= 0.0)
						{
						    op_intrpt_schedule_self (op_sim_time () + control_table[i].start_time, control_table[i].destination);
						}
					}
				
				pk_num = 0;
				
				
				
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** state (init) exit executives **/
			FSM_STATE_EXIT_FORCED (0, "init", "bt_mst_lmp_src_sink [init exit execs]")


			/** state (init) transition processing **/
			FSM_TRANSIT_FORCE (2, state2_enter_exec, ;, "default", "", "init", "idle", "tr_2", "bt_mst_lmp_src_sink [init -> idle : default / ]")
				/*---------------------------------------------------------*/



			/** state (source) enter executives **/
			FSM_STATE_ENTER_FORCED (1, "source", state1_enter_exec, "bt_mst_lmp_src_sink [source enter execs]")
				FSM_PROFILE_SECTION_IN ("bt_mst_lmp_src_sink [source enter execs]", state1_enter_exec)
				{
					send_pkt = OPC_FALSE;
					
					/* Slave addr is used for a dimensioned packet count stat */
					Slave_addr = intrpt_code;
					
					i = 0;
					while (control_table[i].destination != Slave_addr)
						i++;
					
					/*	Generate the packets based on the loaded parameters	*/
					/*	for traffic generation.								*/
					next_packet_arrival_time = op_sim_time () + oms_dist_outcome(control_table[i].int_arrival);
					/*	Create a packet using the outcome of the loaded	*/
					/*	distribution.*/
					pksize = 0;
					while(pksize == 0)
						{
						pksize = floor((SimT_Pk_Size) oms_dist_outcome (control_table[i].pkt_size));
						if (pksize > 17)
							pksize = 17;
						pksize *= 8;
						}
					pkptr  = op_pk_create_fmt ("bt_source");
					op_pk_total_size_set (pkptr, pksize);
					op_pk_nfd_set (pkptr, "pk_count", ++pk_num);
					
					/* Create an ici and set destination and service */
					bt_ici = op_ici_create("bluetooth_mac_ind");
					op_ici_attr_set (bt_ici, "destination", Slave_addr);
					op_ici_attr_set (bt_ici, "QOS", CONTROL);
					op_ici_install(bt_ici);
							
					if (BT_TRACE_ACTIVE)
						{
						sprintf(str0, "Master source generating CONTROL for destination %d ", i); 
						op_prg_odb_print_major (str0, OPC_NIL, OPC_NIL, OPC_NIL);
						}
					send_pkt = OPC_TRUE;
					/* schedule the next packet */
					if (next_packet_arrival_time < control_table[i].stop_time)
						op_intrpt_schedule_self (next_packet_arrival_time, control_table[i].destination);
				
					
					if (send_pkt == OPC_TRUE)
						{
						/*	Record statistics to indicate that a packet 	*/
						/*	was generated at the current simulation time.	*/
						op_stat_write (pksize_stathandle, (double) OPC_TRUE);
				
						/* Update local statistics.				*/
						op_stat_write (bits_sent_stathandle, 		pksize);
						op_stat_write (pkts_sent_stathandle, 		++pkts_sent);
						op_stat_write (pkts_sent_dimstathandle[Slave_addr], ++pk_sent_dim[Slave_addr]);
				
						op_stat_write (bitssec_sent_stathandle, 	pksize);
						op_stat_write (bitssec_sent_stathandle, 	0.0);
						op_stat_write (pktssec_sent_stathandle, 	1.0);
						op_stat_write (pktssec_sent_stathandle, 	0.0);
					
						/* Update global statistics.				*/
						op_stat_write (bits_sent_gstathandle, 		pksize);
						op_stat_write (pkts_sent_gstathandle, 		1.0);
				
						op_stat_write (bitssec_sent_gstathandle, 	pksize);
						op_stat_write (bitssec_sent_gstathandle, 	0.0);
						op_stat_write (pktssec_sent_gstathandle, 	1.0);
						op_stat_write (pktssec_sent_gstathandle, 	0.0);
						
						/* Send the packet to the lower layer.	*/
						op_pk_send (pkptr, 0);
						op_ici_install(OPC_NIL);
						}
					
				}
				FSM_PROFILE_SECTION_OUT (state1_enter_exec)

			/** state (source) exit executives **/
			FSM_STATE_EXIT_FORCED (1, "source", "bt_mst_lmp_src_sink [source exit execs]")
				FSM_PROFILE_SECTION_IN ("bt_mst_lmp_src_sink [source exit execs]", state1_exit_exec)
				{
				/* Determine the type of interrupt.		*/
				intrpt_type = op_intrpt_type ();
				intrpt_code = op_intrpt_code ();
				}
				FSM_PROFILE_SECTION_OUT (state1_exit_exec)


			/** state (source) transition processing **/
			FSM_TRANSIT_FORCE (2, state2_enter_exec, ;, "default", "", "source", "idle", "tr_11", "bt_mst_lmp_src_sink [source -> idle : default / ]")
				/*---------------------------------------------------------*/



			/** state (idle) enter executives **/
			FSM_STATE_ENTER_UNFORCED (2, "idle", state2_enter_exec, "bt_mst_lmp_src_sink [idle enter execs]")

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (5,"bt_mst_lmp_src_sink")


			/** state (idle) exit executives **/
			FSM_STATE_EXIT_UNFORCED (2, "idle", "bt_mst_lmp_src_sink [idle exit execs]")
				FSM_PROFILE_SECTION_IN ("bt_mst_lmp_src_sink [idle exit execs]", state2_exit_exec)
				{
				/* Determine the type of interrupt.		*/
				intrpt_type = op_intrpt_type ();
				intrpt_code = op_intrpt_code ();
				}
				FSM_PROFILE_SECTION_OUT (state2_exit_exec)


			/** state (idle) transition processing **/
			FSM_PROFILE_SECTION_IN ("bt_mst_lmp_src_sink [idle trans conditions]", state2_trans_conds)
			FSM_INIT_COND (SELF_INT)
			FSM_TEST_COND (STRM_INT)
			FSM_DFLT_COND
			FSM_TEST_LOGIC ("idle")
			FSM_PROFILE_SECTION_OUT (state2_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 1, state1_enter_exec, ;, "SELF_INT", "", "idle", "source", "tr_3", "bt_mst_lmp_src_sink [idle -> source : SELF_INT / ]")
				FSM_CASE_TRANSIT (1, 3, state3_enter_exec, ;, "STRM_INT", "", "idle", "discard", "tr_12", "bt_mst_lmp_src_sink [idle -> discard : STRM_INT / ]")
				FSM_CASE_TRANSIT (2, 2, state2_enter_exec, ;, "default", "", "idle", "idle", "tr_14", "bt_mst_lmp_src_sink [idle -> idle : default / ]")
				}
				/*---------------------------------------------------------*/



			/** state (discard) enter executives **/
			FSM_STATE_ENTER_FORCED (3, "discard", state3_enter_exec, "bt_mst_lmp_src_sink [discard enter execs]")

			/** state (discard) exit executives **/
			FSM_STATE_EXIT_FORCED (3, "discard", "bt_mst_lmp_src_sink [discard exit execs]")
				FSM_PROFILE_SECTION_IN ("bt_mst_lmp_src_sink [discard exit execs]", state3_exit_exec)
				{
				/* Obtain the incoming packet.	*/
				intrpt_stream = op_intrpt_strm();
				pkptr = op_pk_get (intrpt_stream);
				
				/* Caclulate metrics to be updated.		*/
				pk_size = (double) op_pk_total_size_get (pkptr);
				ete_delay = op_sim_time () - op_pk_creation_time_get (pkptr);
				
				/* Update local statistics.				*/
				op_stat_write (bits_rcvd_stathandle, 		pk_size);
				op_stat_write (pkts_rcvd_stathandle, 		++pkts_rcvd);
				op_stat_write (ete_delay_stathandle, 		ete_delay);
				
				op_stat_write (bitssec_rcvd_stathandle, 	pk_size);
				op_stat_write (bitssec_rcvd_stathandle, 	0.0);
				op_stat_write (pktssec_rcvd_stathandle, 	1.0);
				op_stat_write (pktssec_rcvd_stathandle, 	0.0);
				
				/* Update global statistics.	*/
				op_stat_write (bits_rcvd_gstathandle, 		pk_size);
				op_stat_write (pkts_rcvd_gstathandle, 		1.0);
				op_stat_write (ete_delay_gstathandle, 		ete_delay);
				
				op_stat_write (bitssec_rcvd_gstathandle, 	pk_size);
				op_stat_write (bitssec_rcvd_gstathandle, 	0.0);
				op_stat_write (pktssec_rcvd_gstathandle, 	1.0);
				op_stat_write (pktssec_rcvd_gstathandle, 	0.0);
				
				/* Destroy the received packet.	*/
				op_pk_destroy (pkptr);
				
				}
				FSM_PROFILE_SECTION_OUT (state3_exit_exec)


			/** state (discard) transition processing **/
			FSM_TRANSIT_FORCE (2, state2_enter_exec, ;, "default", "", "discard", "idle", "tr_13", "bt_mst_lmp_src_sink [discard -> idle : default / ]")
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"bt_mst_lmp_src_sink")
		}
	}




void
_op_bt_mst_lmp_src_sink_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}




void
_op_bt_mst_lmp_src_sink_terminate (OP_SIM_CONTEXT_ARG_OPT)
	{

	FIN_MT (_op_bt_mst_lmp_src_sink_terminate ())


	/* No Termination Block */

	Vos_Poolmem_Dealloc (pr_state_ptr);

	FOUT
	}


/* Undefine shortcuts to state variables to avoid */
/* syntax error in direct access to fields of */
/* local variable prs_ptr in _op_bt_mst_lmp_src_sink_svar function. */
#undef pksize_stathandle
#undef bits_sent_stathandle
#undef bitssec_sent_stathandle
#undef pkts_sent_stathandle
#undef pktssec_sent_stathandle
#undef bits_sent_gstathandle
#undef bitssec_sent_gstathandle
#undef pkts_sent_gstathandle
#undef pktssec_sent_gstathandle
#undef dest_addr
#undef pkts_sent
#undef pk_num
#undef pkts_sent_dimstathandle
#undef pk_sent_dim
#undef Slave_addr
#undef control_table
#undef num_control_connections
#undef bits_rcvd_stathandle
#undef bitssec_rcvd_stathandle
#undef pkts_rcvd_stathandle
#undef pktssec_rcvd_stathandle
#undef ete_delay_stathandle
#undef bits_rcvd_gstathandle
#undef bitssec_rcvd_gstathandle
#undef pkts_rcvd_gstathandle
#undef pktssec_rcvd_gstathandle
#undef ete_delay_gstathandle
#undef pkts_rcvd
#undef control_bitssec_rcvd_stathandle
#undef control_pkts_rcvd_stathandle
#undef control_ete_delay_stathandle
#undef control_pkts_rcvd

#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

VosT_Obtype
_op_bt_mst_lmp_src_sink_init (int * init_block_ptr)
	{
	VosT_Obtype obtype = OPC_NIL;
	FIN_MT (_op_bt_mst_lmp_src_sink_init (init_block_ptr))

	obtype = Vos_Define_Object_Prstate ("proc state vars (bt_mst_lmp_src_sink)",
		sizeof (bt_mst_lmp_src_sink_state));
	*init_block_ptr = 0;

	FRET (obtype)
	}

VosT_Address
_op_bt_mst_lmp_src_sink_alloc (VosT_Obtype obtype, int init_block)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	bt_mst_lmp_src_sink_state * ptr;
	FIN_MT (_op_bt_mst_lmp_src_sink_alloc (obtype))

	ptr = (bt_mst_lmp_src_sink_state *)Vos_Alloc_Object (obtype);
	if (ptr != OPC_NIL)
		{
		ptr->_op_current_block = init_block;
#if defined (OPD_ALLOW_ODB)
		ptr->_op_current_state = "bt_mst_lmp_src_sink [init enter execs]";
#endif
		}
	FRET ((VosT_Address)ptr)
	}



void
_op_bt_mst_lmp_src_sink_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	bt_mst_lmp_src_sink_state		*prs_ptr;

	FIN_MT (_op_bt_mst_lmp_src_sink_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (bt_mst_lmp_src_sink_state *)gen_ptr;

	if (strcmp ("pksize_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pksize_stathandle);
		FOUT
		}
	if (strcmp ("bits_sent_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bits_sent_stathandle);
		FOUT
		}
	if (strcmp ("bitssec_sent_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bitssec_sent_stathandle);
		FOUT
		}
	if (strcmp ("pkts_sent_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pkts_sent_stathandle);
		FOUT
		}
	if (strcmp ("pktssec_sent_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pktssec_sent_stathandle);
		FOUT
		}
	if (strcmp ("bits_sent_gstathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bits_sent_gstathandle);
		FOUT
		}
	if (strcmp ("bitssec_sent_gstathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bitssec_sent_gstathandle);
		FOUT
		}
	if (strcmp ("pkts_sent_gstathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pkts_sent_gstathandle);
		FOUT
		}
	if (strcmp ("pktssec_sent_gstathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pktssec_sent_gstathandle);
		FOUT
		}
	if (strcmp ("dest_addr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->dest_addr);
		FOUT
		}
	if (strcmp ("pkts_sent" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pkts_sent);
		FOUT
		}
	if (strcmp ("pk_num" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pk_num);
		FOUT
		}
	if (strcmp ("pkts_sent_dimstathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (prs_ptr->pkts_sent_dimstathandle);
		FOUT
		}
	if (strcmp ("pk_sent_dim" , var_name) == 0)
		{
		*var_p_ptr = (void *) (prs_ptr->pk_sent_dim);
		FOUT
		}
	if (strcmp ("Slave_addr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->Slave_addr);
		FOUT
		}
	if (strcmp ("control_table" , var_name) == 0)
		{
		*var_p_ptr = (void *) (prs_ptr->control_table);
		FOUT
		}
	if (strcmp ("num_control_connections" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->num_control_connections);
		FOUT
		}
	if (strcmp ("bits_rcvd_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bits_rcvd_stathandle);
		FOUT
		}
	if (strcmp ("bitssec_rcvd_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bitssec_rcvd_stathandle);
		FOUT
		}
	if (strcmp ("pkts_rcvd_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pkts_rcvd_stathandle);
		FOUT
		}
	if (strcmp ("pktssec_rcvd_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pktssec_rcvd_stathandle);
		FOUT
		}
	if (strcmp ("ete_delay_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->ete_delay_stathandle);
		FOUT
		}
	if (strcmp ("bits_rcvd_gstathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bits_rcvd_gstathandle);
		FOUT
		}
	if (strcmp ("bitssec_rcvd_gstathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bitssec_rcvd_gstathandle);
		FOUT
		}
	if (strcmp ("pkts_rcvd_gstathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pkts_rcvd_gstathandle);
		FOUT
		}
	if (strcmp ("pktssec_rcvd_gstathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pktssec_rcvd_gstathandle);
		FOUT
		}
	if (strcmp ("ete_delay_gstathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->ete_delay_gstathandle);
		FOUT
		}
	if (strcmp ("pkts_rcvd" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pkts_rcvd);
		FOUT
		}
	if (strcmp ("control_bitssec_rcvd_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->control_bitssec_rcvd_stathandle);
		FOUT
		}
	if (strcmp ("control_pkts_rcvd_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->control_pkts_rcvd_stathandle);
		FOUT
		}
	if (strcmp ("control_ete_delay_stathandle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->control_ete_delay_stathandle);
		FOUT
		}
	if (strcmp ("control_pkts_rcvd" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->control_pkts_rcvd);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

