File format:	operation list

start_operation
	title:	"SuiteTooth Project"
	position: 	4
end_operation

#########################################

start_operation
	operation:			go_file SuiteTooth_project_exec
	menu string:		"Create SuiteTooth model"
	menu header:		"SuiteTooth Project"
	guidance string:        "Create new SuiteTooth model"
	position:			110
end_operation

start_operation
	operation:			go_file SuiteTooth_project_exec
	icon:				wireless_laptop
	guidance string:        "Create new SuiteTooth model"
end_operation


