/* Process model C++ form file: wban_tcp_server_trail_child.pr.cpp */
/* Portions of this file copyright 2014 by Riverbed Technology. All rights reserved. */


/*
 =========================== NOTE ==========================
 This file is automatically generated from wban_tcp_server_trail_child.pr.m
 during a process model compilation.

 Do NOT manually edit this file.
 Manual edits will be lost during the next compilation.
 =========================== NOTE ==========================
*/



/* This variable carries the header into the object file */
const char wban_tcp_server_trail_child_pr_cpp [] = "MIL_3_Tfile_Hdr_ 1800 30A modeler 7 571D60A9 571D60A9 1 volta chaganti 0 0 none none 0 0 none 0 0 0 0 0 0 0 0 468d 2                                                                                                                                                                                                                                                                                                                                                                                                           ";
#include <string.h>



/* OPNET system definitions */
#include <opnet.h>



/* Header Block */

#include "ip_addr_v4.h"
#include "tcp_api_v3.h"
#include <stdio.h>
#include <bgp.h>
#include <tcp_v3.h>
#include <string.h>
//#include "1508_lab3_real_payload_support.h"

/*	Define constants used in the process model.			*/
#define	TCP_LAB_GEN_CONN_OPEN		100
#define	TCP_LAB_GEN_CONN_CLOSE		200
#define TCP_LAB_GEN_PK_CREATE		300

/*	State transition macro definitions.					*/
#define	TCP_CONN_OPEN			((op_intrpt_type () == OPC_INTRPT_SELF) && \
							 (op_intrpt_code () == TCP_LAB_GEN_CONN_OPEN))

//#define CONN_ESTABLISHED	((intrpt_type == OPC_INTRPT_REMOTE) &&	\
							 (intrpt_code == TCPC_IND_CONNECT_REQUEST))

#define	PKT_RECEIVE			(op_intrpt_type () == OPC_INTRPT_STRM)

#define	CONN_RELEASE		((op_intrpt_type () == OPC_INTRPT_REMOTE) && \
							 (op_intrpt_code () == TCPC_IND_FIN_RECEIVED ||\
							  op_intrpt_code () == TCPC_IND_CLOSED))

#define	TCP_INTRPT			(intrpt_type == OPC_INTRPT_REMOTE && \
							 intrpt_code == TCPC_IND_NONE)

#define TCP_OPEN_IND			(intrpt_type == OPC_INTRPT_REMOTE && \
								intrpt_code == TCPC_IND_CONNECT_REQUEST)

/* TCP event codes */
#define CONN_OPEN 					0
#define OPEN_IND					1
#define OPEN_CONFIRM				2
#define RECEIVE						3
#define RELEASE						4


void						server_passive_transport_conn_open (void* PRG_ARG_UNUSED (state_ptr), int PRG_ARG_UNUSED (code));
static void 				bgp_neighbor_processes_create ();

char *Ip_addr[] = {"192.0.0.6", "192.0.0.10", "192.0.0.13"};

/* End of Header Block */

#if !defined (VOSD_NO_FIN)
#undef	BIN
#undef	BOUT
#define	BIN		FIN_LOCAL_FIELD(_op_last_line_passed) = __LINE__ - _op_block_origin;
#define	BOUT	BIN
#define	BINIT	FIN_LOCAL_FIELD(_op_last_line_passed) = 0; _op_block_origin = __LINE__;
#else
#define	BINIT
#endif /* #if !defined (VOSD_NO_FIN) */



/* State variable definitions */
class wban_tcp_server_trail_child_state
	{
	private:
		/* Internal state tracking for FSM */
		FSM_SYS_STATE

	public:
		wban_tcp_server_trail_child_state (void);

		/* Destructor contains Termination Block */
		~wban_tcp_server_trail_child_state (void);

		/* State Variables */
		Objid	                  		my_id                                           ;
		TcpT_Port	              		local_port                                      ;
		TcpT_Port	              		remote_port                                     ;
		InetT_Address	          		remote_inet_ip_addr                             ;
		ApiT_Tcp_App_Handle	    		tcp_app_handle                                  ;
		int	                    		connect_id                                      ;
		InetT_Address	          		inet_address                                    ;
		TcpT_Conn_Open_Options	 		conn_options                                    ;
		InetT_Address	          		local_inet_ip_addr                              ;
		Ici*	                   		command_ici_ptr                                 ;
		Ici*	                   		tcp_open_ind_ici_ptr                            ;
		FILE*	                  		pFile                                           ;
		int	                    		stream_count                                    ;
		int	                    		child_count                                     ;
		Prohandle*	             		child_proc                                      ;
		int	                    		event                                           ;
		List*	                  		bgp_connections_list_ptr                        ;
		char	                   		bgp_error_str[256]                              ;
		TcpT_Event*	            		ev_ptr                                          ;
		int	                    		next_avail_peer_id                              ;
		int	                    		num_pkts                                        ;
		Objid	                  		parent_id                                       ;
		int	                    		conn_id                                         ;

		/* FSM code */
		void wban_tcp_server_trail_child (OP_SIM_CONTEXT_ARG_OPT);
		/* Diagnostic Block */
		void _op_wban_tcp_server_trail_child_diag (OP_SIM_CONTEXT_ARG_OPT);

#if defined (VOSD_NEW_BAD_ALLOC)
		void * operator new (size_t) throw (VOSD_BAD_ALLOC);
#else
		void * operator new (size_t);
#endif
		void operator delete (void *);

		/* Memory management */
		static VosT_Obtype obtype;
	};

VosT_Obtype wban_tcp_server_trail_child_state::obtype = (VosT_Obtype)OPC_NIL;

#define pr_state_ptr            		((wban_tcp_server_trail_child_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr))
#define my_id                   		pr_state_ptr->my_id
#define local_port              		pr_state_ptr->local_port
#define remote_port             		pr_state_ptr->remote_port
#define remote_inet_ip_addr     		pr_state_ptr->remote_inet_ip_addr
#define tcp_app_handle          		pr_state_ptr->tcp_app_handle
#define connect_id              		pr_state_ptr->connect_id
#define inet_address            		pr_state_ptr->inet_address
#define conn_options            		pr_state_ptr->conn_options
#define local_inet_ip_addr      		pr_state_ptr->local_inet_ip_addr
#define command_ici_ptr         		pr_state_ptr->command_ici_ptr
#define tcp_open_ind_ici_ptr    		pr_state_ptr->tcp_open_ind_ici_ptr
#define pFile                   		pr_state_ptr->pFile
#define stream_count            		pr_state_ptr->stream_count
#define child_count             		pr_state_ptr->child_count
#define child_proc              		pr_state_ptr->child_proc
#define event                   		pr_state_ptr->event
#define bgp_connections_list_ptr		pr_state_ptr->bgp_connections_list_ptr
#define bgp_error_str           		pr_state_ptr->bgp_error_str
#define ev_ptr                  		pr_state_ptr->ev_ptr
#define next_avail_peer_id      		pr_state_ptr->next_avail_peer_id
#define num_pkts                		pr_state_ptr->num_pkts
#define parent_id               		pr_state_ptr->parent_id
#define conn_id                 		pr_state_ptr->conn_id

/* These macro definitions will define a local variable called	*/
/* "op_sv_ptr" in each function containing a FIN statement.	*/
/* This variable points to the state variable data structure,	*/
/* and can be used from a C debugger to display their values.	*/
#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE
#define FIN_PREAMBLE_DEC	wban_tcp_server_trail_child_state *op_sv_ptr;
#define FIN_PREAMBLE_CODE	\
		op_sv_ptr = ((wban_tcp_server_trail_child_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr));


/* Function Block */

#if !defined (VOSD_NO_FIN)
enum { _op_block_origin = __LINE__ + 2};
#endif

void
server_passive_transport_conn_open (void* PRG_ARG_UNUSED (state_ptr), int PRG_ARG_UNUSED (code))
	{
	
	/** This function will open a passive tcp connection to listen to 	**/
	/** port  	waiting for other neighbors to initiate a tcp open.	**/
	
	FIN (server_passive_transport_conn_open (state_ptr, code))
		
	/* Populate the given options structure with the 		*/
	/* default ones.										*/
	tcp_conn_open_default_options_set (&conn_options);
	
	//tcp_conn_open_options_local_port_set (&options, TCPC_BGP_RESERVED_PORT) /* For a reserved port */
	
	/* No need to use copy of address. A copy will be   	*/
	/* created by tcp_connection_open_with_options ().		*/
    tcp_conn_open_options_local_addr_set (&conn_options, local_inet_ip_addr); 
	
	/* Allocate memory for the pointer to					*/
	/* OmsT_Sar_Payload_Process_Callbacks					*/
//	ser_callbacks_ptr = (OmsT_Sar_Payload_Process_Callbacks*) prg_mem_alloc (sizeof (OmsT_Sar_Payload_Process_Callbacks));

	/* Set the callbacks that will translate OPNET packets	*/
	/* into real byte streams set as the payload of real 	*/
	/* TCP messages											*/      
//	ser_callbacks_ptr->serialize_func = tcp_sar_serialization_callback;
//	ser_callbacks_ptr->deserialize_func = tcp_sar_deserialization_callback;
	
	/* Set the callbacks into the conn_options that we will	*/
	/* pass to tcp_connection_open_with_options().			*/
//	conn_options.ser_callbacks_ptr = ser_callbacks_ptr;
		
	/* Open a passive TCP connection and wait for an  		*/
	/* incoming request from the client. The struct  		*/
	/* conn_options also contains pointers to the callback  */
	/* functions for serialization and deserialization.		*/
	conn_id = tcp_connection_open_with_options (&tcp_app_handle, INETC_ADDRESS_INVALID, 
		TCPC_PORT_UNSPEC, TCPC_COMMAND_OPEN_PASSIVE, &conn_options);
	
	/*	Generate trace messsage								*/
	if (op_prg_odb_ltrace_active ("tcp"))
		{
		op_prg_odb_print_major ("server: TCP Passive Open", OPC_NIL);
		}
	printf("Opened passive connection id : %d\n", conn_id);

	FOUT;
	}
static BgpT_Conn_Info*
bgp_connection_info_from_conn_id_get (int tcp_conn_id)
	{
	BgpT_Conn_Info*	ith_bgp_conn_info_ptr;
	int				num_bgp_connections;
	int				count_i;

	/** This fucnction will parse through the entire list of available 	**/
	/** connections and returns a reference to the neighbor process		**/
	/** whose TCP connection ID matches the given tcp_conn_id.			**/
	FIN (bgp_connection_info_from_conn_id_get (tcp_conn_id))

	/* Obtain the number of the connections present. 					*/
	num_bgp_connections = op_prg_list_size (bgp_connections_list_ptr);

	/* Scan through the list of available neighbor processes.			*/
	for (count_i = 0; count_i < num_bgp_connections; count_i++)
		{
		ith_bgp_conn_info_ptr = (BgpT_Conn_Info*) op_prg_list_access (bgp_connections_list_ptr, count_i);

		/* Having obtained the connection information, check to see if 	*/
		/* the tcp_conn_id of this connection matches the given conn_id */
		if (ith_bgp_conn_info_ptr->tcp_connection_id == tcp_conn_id)
			{
			/* We found a match. Return the	connection information. 	*/
			FRET (ith_bgp_conn_info_ptr);
			}

		/* Continue to search the entire list till a matching process	*/
		/* can be obtained.												*/
		}

	/* A corresponding BGP connection could not be found. Return NULL 	*/
	FRET (OPC_NIL);
	}

static void
bgp_fatal_error (const char* msg_str)
    {
    /** An error is termed fatal if the simulation simply   **/
    /** cannot progress after encountering the error. Most  **/
    /** of the fatal errors occur when it is unable to      **/
    /** allocate memory.                                    **/
    FIN (bgp_fatal_error (char* msg_str))
 
    op_sim_end (bgp_error_str, msg_str, 
		"Please refer to the simulation log for details", 
		OPC_NIL);
 
    FOUT;
    }

static BgpT_Conn_Info*
bgp_ptc_mem_create (InetT_Address remote_addr, ApiT_Tcp_App_Handle tcp_intf_hndl)
	{
	BgpT_Conn_Info*					bgp_conn_info_ptr;
	char 							remote_addr_string[25];

	/** This function creates a parent child shared memory block and 	**/
	/** fills in the given details and returns a reference.  			**/
	FIN (bgp_ptc_mem_create (remote_addr, tcp_passive_process_hndl));
		
	/* Allocate memory for the new parent child memory block.			*/
	bgp_conn_info_ptr = (BgpT_Conn_Info*) op_prg_mem_alloc (sizeof (BgpT_Conn_Info));
	

	/* Set the value of the remote address and the TCP interface handle */
	/* passed in as arguments.											*/
	//bgp_conn_info_ptr->neighbor_ip_address 	= inet_address_copy (remote_addr);

	bgp_conn_info_ptr->neighbor_ip_address 	= inet_address_copy (remote_addr);
	bgp_conn_info_ptr->update_source_addr  = inet_address_copy (INETC_ADDRESS_INVALID);	
	inet_address_print(remote_addr_string, remote_addr);
	printf("Remote address that is in connection with server: %s\n", remote_addr_string);
	


	/* Intialize all other memebers of this data structure.				*/
	
	bgp_conn_info_ptr->tcp_connection_id 	= TCPC_CONN_ID_UNSPEC;
	bgp_conn_info_ptr->tcp_intf_handle		= tcp_intf_hndl;
	
	bgp_conn_info_ptr->peer_id = ++next_avail_peer_id;

	bgp_conn_info_ptr->flags = 0;
	printf("created memory bgp conn info\n");

	FRET (bgp_conn_info_ptr);
	}



static void
bgp_neighbor_processes_create ()
	{
	BgpT_Conn_Info		*bgp_conn_info_ptr;
	int					neighbor_count;
	int					count_i;
	char				ip_addr_str [256], description_str [256];
	InetT_Address		remote_address;
    char			   	update_source_str [256];
	InetT_Address		update_source_addr;



	/** This function reads the entries of the BGP Neighbor	information	**/
	/** compound attribute and spawns a BGP connection process for each **/
	/** of its configured neighbours.									**/
	FIN (bgp_neighbor_processes_create (TcpT_Event* ev_ptr));


	neighbor_count = 2;
	
	/* Scan through the entries and spawn a connection process for each */
	/* of these entries.												*/ 
	for (count_i = 0; count_i < neighbor_count; count_i++)
		{
				
		/****************************************************************/
		/* ADDRESS 														*/					
		/****************************************************************/
		
		strcpy(ip_addr_str, Ip_addr[count_i]);
		printf("IP address dtr : %s \n", ip_addr_str);
		/* Create an IP address in the internal representation format.	*/
		remote_address = inet_address_create (ip_addr_str, InetC_Addr_Family_Unknown);
			
		
		/* Allocate memory for the information that will be shared 	*/
		/* between this process (bgp) and the child (bgp_conn).  	*/
		bgp_conn_info_ptr = bgp_ptc_mem_create (remote_address,  tcp_app_handle);

		
//		ev_ptr->event = CONN_OPEN;
//			printf("OPEN ID indicator : %d\n", ev_ptr->event);
			bgp_conn_info_ptr->bgp_connection_prohandle = op_pro_create ("wban_tcp_server_trail", bgp_conn_info_ptr);
			op_pro_invoke (bgp_conn_info_ptr->bgp_connection_prohandle, OPC_NIL);
		
	
	printf("Child process invoke success \n");
		
		/* The conn_info data structure will be inserted into the	*/
		/* list connection information of all the BGP connections 	*/
		/* maintained by this bgp process. Any time a message comes */
		/* in from the lower layer this information will be used to	*/
		/* find out the connection process to which the message is	*/
		/* intended and will be delivered.							*/
		op_prg_list_insert (bgp_connections_list_ptr, bgp_conn_info_ptr, OPC_LISTPOS_HEAD);

		} /* End all neighbors on this node	*/

	FOUT;
	}

/* End of Function Block */

/* Undefine optional tracing in FIN/FOUT/FRET */
/* The FSM has its own tracing code and the other */
/* functions should not have any tracing.		  */
#undef FIN_TRACING
#define FIN_TRACING

#undef FOUTRET_TRACING
#define FOUTRET_TRACING

/* Undefine shortcuts to state variables because the */
/* following functions are part of the state class */
#undef my_id
#undef local_port
#undef remote_port
#undef remote_inet_ip_addr
#undef tcp_app_handle
#undef connect_id
#undef inet_address
#undef conn_options
#undef local_inet_ip_addr
#undef command_ici_ptr
#undef tcp_open_ind_ici_ptr
#undef pFile
#undef stream_count
#undef child_count
#undef child_proc
#undef event
#undef bgp_connections_list_ptr
#undef bgp_error_str
#undef ev_ptr
#undef next_avail_peer_id
#undef num_pkts
#undef parent_id
#undef conn_id

/* Access from C kernel using C linkage */
extern "C"
{
	VosT_Obtype _op_wban_tcp_server_trail_child_init (int * init_block_ptr);
	VosT_Address _op_wban_tcp_server_trail_child_alloc (VosT_Obtype, int);
	void wban_tcp_server_trail_child (OP_SIM_CONTEXT_ARG_OPT)
		{
		((wban_tcp_server_trail_child_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr))->wban_tcp_server_trail_child (OP_SIM_CONTEXT_PTR_OPT);
		}

	void _op_wban_tcp_server_trail_child_svar (void *, const char *, void **);

	void _op_wban_tcp_server_trail_child_diag (OP_SIM_CONTEXT_ARG_OPT)
		{
		((wban_tcp_server_trail_child_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr))->_op_wban_tcp_server_trail_child_diag (OP_SIM_CONTEXT_PTR_OPT);
		}

	void _op_wban_tcp_server_trail_child_terminate (OP_SIM_CONTEXT_ARG_OPT)
		{
		/* The destructor is the Termination Block */
		delete (wban_tcp_server_trail_child_state *)(OP_SIM_CONTEXT_PTR->_op_mod_state_ptr);
		}


} /* end of 'extern "C"' */




/* Process model interrupt handling procedure */


void
wban_tcp_server_trail_child_state::wban_tcp_server_trail_child (OP_SIM_CONTEXT_ARG_OPT)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	FIN_MT (wban_tcp_server_trail_child_state::wban_tcp_server_trail_child ());
	try
		{
		/* Temporary Variables */
		Packet*			pkptr;
		int				intrpt_type;
		int				intrpt_code;
		int				tcp_conn_id;
		OpT_uInt32		incoming_payload;
		char 			msg0[256];
		/* Holds the return value from searching the list of  bgp connections.	*/
		BgpT_Conn_Info* 	bgp_conn_info_ptr;
		Ici*				transport_ici_ptr;
		
		InetT_Address		remote_addr, *remote_addr_ptr;
		static Pmohandle	ev_pmh;
		char				local_addr_str[25];
		char	temp_addr_str[25];
		/* End of Temporary Variables */


		FSM_ENTER ("wban_tcp_server_trail_child")

		FSM_BLOCK_SWITCH
			{
			/*---------------------------------------------------------*/
			/** state (INIT) enter executives **/
			FSM_STATE_ENTER_UNFORCED_NOLABEL (0, "INIT", "wban_tcp_server_trail_child [INIT enter execs]")
				FSM_PROFILE_SECTION_IN ("wban_tcp_server_trail_child [INIT enter execs]", state0_enter_exec)
				{
				/*	Obtain the object ID of this process' surrounding module.	*/
				my_id = op_id_self ();
				
				
				/* obtain object ID of the parent object (node) */
				parent_id = op_topo_parent (my_id);
				
				
				/* Read the parameters of Remote Address,Remote Port */	
							
				op_ima_obj_attr_get (parent_id, "server.Remote IP Address", local_addr_str);
				printf("Server Remote Address : %s\n", local_addr_str);
				
				/*	Schedule the start of operation.							*/
				op_intrpt_schedule_self (op_sim_time (), TCP_LAB_GEN_CONN_OPEN);
				
				/*	Create the inet IP address 									*/
				local_inet_ip_addr = inet_address_from_ipv4_address_create (ip_address_create (local_addr_str));
				
				/* This application must register itself with the TCP API. The	*/
				/* API handle will be used on all subsequent calls to the API.	*/
				tcp_app_handle = tcp_app_register (my_id);
				
				
				
				ev_pmh = op_prg_pmo_define ("wban_tcp_server_trail event", sizeof (TcpT_Event), 16);
				
				
				/*	Without memory to hold the event, this model will be disabled.	*/
				ev_ptr = (TcpT_Event *) op_prg_pmo_alloc (ev_pmh);
				
				//ev_ptr = (TcpT_Event *) op_prg_mem_alloc(sizeof(TcpT_Event));
				
				next_avail_peer_id = 0;
				
				/* Open the output file in which we will add the contents of 	*/
				/* received application packets.								*/
				//pFile = fopen ("C:\\op_models\\1508_lab3_server_output.txt", "w"); 
				
				/*if (!pFile)
					{
					op_sim_end ("Output file could not be opened.", "", "", "");
					} */
				
				/* Count input streams */
				//stream_count = op_topo_assoc_count (op_id_self(), OPC_TOPO_ASSOC_IN, OPC_OBJTYPE_STRM);
				//stream_count = 10;
				//printf("Stream count : %d\n", stream_count);
				
				/* Allocate array for child process handles */
				//child_proc = (Prohandle *) op_prg_mem_alloc (stream_count * sizeof (Prohandle));
				
				/* Create child process(es) */
				//for (int i = 0; i < stream_count; i++)
				//	{
					/* #1A */
				//	child_proc[i] = op_pro_create("wban_tcp_server_trail", OPC_NIL);
					/* #2A */
				//	}
				//op_intrpt_schedule_self(op_sim_time(), TCP_LAB_GEN_CONN_OPEN);
				
				/* Create the list for BGP peer process maintained from this node. 	*/
					/* This list is referred to whenever a packet reaches the dispatch. */
					bgp_connections_list_ptr = op_prg_list_create ();
				}
				FSM_PROFILE_SECTION_OUT (state0_enter_exec)

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (1,"wban_tcp_server_trail_child")


			/** state (INIT) exit executives **/
			FSM_STATE_EXIT_UNFORCED (0, "INIT", "wban_tcp_server_trail_child [INIT exit execs]")


			/** state (INIT) transition processing **/
			FSM_TRANSIT_ONLY ((TCP_CONN_OPEN), 1, state1_enter_exec, ;, INIT, "TCP_CONN_OPEN", "", "INIT", "CREATE_CONN", "tr_121", "wban_tcp_server_trail_child [INIT -> CREATE_CONN : TCP_CONN_OPEN / ]")
				/*---------------------------------------------------------*/



			/** state (CREATE_CONN) enter executives **/
			FSM_STATE_ENTER_FORCED (1, "CREATE_CONN", state1_enter_exec, "wban_tcp_server_trail_child [CREATE_CONN enter execs]")
				FSM_PROFILE_SECTION_IN ("wban_tcp_server_trail_child [CREATE_CONN enter execs]", state1_enter_exec)
				{
				/* Open a passive TCP connection that would be listening on the port 	*/
				server_passive_transport_conn_open (OPC_NIL, OPC_NIL);
				
						//ev_ptr->event = CONN_OPEN;
				
				
				//bgp_neighbor_processes_create();
				}
				FSM_PROFILE_SECTION_OUT (state1_enter_exec)

			/** state (CREATE_CONN) exit executives **/
			FSM_STATE_EXIT_FORCED (1, "CREATE_CONN", "wban_tcp_server_trail_child [CREATE_CONN exit execs]")


			/** state (CREATE_CONN) transition processing **/
			FSM_TRANSIT_FORCE (5, state5_enter_exec, ;, "default", "", "CREATE_CONN", "idle", "tr_122", "wban_tcp_server_trail_child [CREATE_CONN -> idle : default / ]")
				/*---------------------------------------------------------*/



			/** state (RECEIVE) enter executives **/
			FSM_STATE_ENTER_FORCED (2, "RECEIVE", state2_enter_exec, "wban_tcp_server_trail_child [RECEIVE enter execs]")
				FSM_PROFILE_SECTION_IN ("wban_tcp_server_trail_child [RECEIVE enter execs]", state2_enter_exec)
				{
				if (PKT_RECEIVE)
					{
					
				printf("---PACKET SERVER RECEIVE PARENT--- \n");
				/* ev_ptr is 2 for Receive) */
				//op_pro_invoke(child_proc[i], event);
					
					/* Block specific variables.											*/
				BgpT_Tcp_Conn_Status	tcp_conn_status;
				
				
				/* Obtain the ICI accompanying the interrupt.							*/
				transport_ici_ptr = op_intrpt_ici ();
				
				if (transport_ici_ptr == OPC_NIL)
					{
					op_sim_end ("Unable to obtain ICI associated with the interrupt",
								OPC_NIL, OPC_NIL, OPC_NIL);
					}
				
				/* Get the connection ID from the received ICI.							*/
				op_ici_attr_get (transport_ici_ptr, "conn_id", &tcp_conn_id);
				op_ici_attr_get (transport_ici_ptr, "status",  &tcp_conn_status);
				
				/* Get the bgp connection details with the transport connection ID.		*/
				bgp_conn_info_ptr = (BgpT_Conn_Info*) bgp_connection_info_from_conn_id_get (tcp_conn_id);
				
				if (bgp_conn_info_ptr == OPC_NIL)
					{
					/* If a link or node goes down, we might continue to get TCP		*/
					/* Until TCP is properly fixed, just ignore them.					*/
					/*bgp_fatal_error ("In Open Confirm. Unable to map the tcp conn id to a bgp conn process");*/
					}
				else
				    {
					/* Invoke the connection.*/
					ev_ptr->event = RECEIVE;
					op_pro_invoke (bgp_conn_info_ptr->bgp_connection_prohandle, ev_ptr);
					}
					
				/* Also destroy the ICI from the TCP layer.							*/
				//op_ici_destroy (transport_ici_ptr);
					}
				
				
				
				}
				FSM_PROFILE_SECTION_OUT (state2_enter_exec)

			/** state (RECEIVE) exit executives **/
			FSM_STATE_EXIT_FORCED (2, "RECEIVE", "wban_tcp_server_trail_child [RECEIVE exit execs]")


			/** state (RECEIVE) transition processing **/
			FSM_TRANSIT_FORCE (5, state5_enter_exec, ;, "default", "", "RECEIVE", "idle", "tr_71", "wban_tcp_server_trail_child [RECEIVE -> idle : default / ]")
				/*---------------------------------------------------------*/



			/** state (RELEASE) enter executives **/
			FSM_STATE_ENTER_FORCED (3, "RELEASE", state3_enter_exec, "wban_tcp_server_trail_child [RELEASE enter execs]")
				FSM_PROFILE_SECTION_IN ("wban_tcp_server_trail_child [RELEASE enter execs]", state3_enter_exec)
				{
				if (CONN_RELEASE)
					{
					printf("------CONNECTION RELEASE SERVR---- \n");
				/* Block specific variables.											*/
				BgpT_Tcp_Conn_Status	tcp_conn_status;
				
				/* Obtain the ICI accompanying the interrupt.							*/
				transport_ici_ptr = op_intrpt_ici ();
				
				if (transport_ici_ptr == OPC_NIL)
					{
					op_sim_end ("Unable to obtain ICI associated with the interrupt",
								OPC_NIL, OPC_NIL, OPC_NIL);
					}
				
				/* Get the connection ID from the received ICI.							*/
				op_ici_attr_get (transport_ici_ptr, "conn_id", &tcp_conn_id);
				op_ici_attr_get (transport_ici_ptr, "status",  &tcp_conn_status);
				
				/* Get the bgp connection details with the transport connection ID.		*/
				bgp_conn_info_ptr = (BgpT_Conn_Info*) bgp_connection_info_from_conn_id_get (tcp_conn_id);
				
				if (bgp_conn_info_ptr == OPC_NIL)
					{
					/* If a link or node goes down, we might continue to get TCP		*/
					/* Until TCP is properly fixed, just ignore them.					*/
					/*bgp_fatal_error ("In Open Confirm. Unable to map the tcp conn id to a bgp conn process");*/
					}
				else
				    {
					/* Invoke the connection.*/
					ev_ptr->event = RELEASE;
					op_pro_invoke (bgp_conn_info_ptr->bgp_connection_prohandle, ev_ptr);
					}
					
				/* Also destroy the ICI from the TCP layer.							*/
				op_ici_destroy (transport_ici_ptr);
					}
				//op_pro_invoke(child_proc[0], event);
				/* ev_ptr is 3 for Release) */
				}
				FSM_PROFILE_SECTION_OUT (state3_enter_exec)

			/** state (RELEASE) exit executives **/
			FSM_STATE_EXIT_FORCED (3, "RELEASE", "wban_tcp_server_trail_child [RELEASE exit execs]")


			/** state (RELEASE) transition processing **/
			FSM_TRANSIT_FORCE (5, state5_enter_exec, ;, "default", "", "RELEASE", "idle", "tr_67", "wban_tcp_server_trail_child [RELEASE -> idle : default / ]")
				/*---------------------------------------------------------*/



			/** state (OPEN_CNFRM) enter executives **/
			FSM_STATE_ENTER_FORCED (4, "OPEN_CNFRM", state4_enter_exec, "wban_tcp_server_trail_child [OPEN_CNFRM enter execs]")
				FSM_PROFILE_SECTION_IN ("wban_tcp_server_trail_child [OPEN_CNFRM enter execs]", state4_enter_exec)
				{
				/** Any other remote indication from TCP except the one when a remote	**/
				/** neighbor is attempting to connect to the passive connection is		**/
				/** handled in this state.												**/
				
				/** BGP has received a OPEN confirm from TCP indicating the transport	**/
				/** connection has been successfully established. This information has 	**/
				/** to be passed on to the appropriate neighbor process, so that the 	**/
				/** FSM can correspondingly transition and send out BGP OPEN messages.	**/
				 
				/* Block specific variables.											*/
				BgpT_Tcp_Conn_Status	tcp_conn_status;
				
				/* Obtain the ICI accompanying the interrupt.							*/
				transport_ici_ptr = op_intrpt_ici ();
				
				if (transport_ici_ptr == OPC_NIL)
					{
					op_sim_end ("Unable to obtain ICI associated with the interrupt",
								OPC_NIL, OPC_NIL, OPC_NIL);
					}
				
				/* Get the connection ID from the received ICI.							*/
				op_ici_attr_get (transport_ici_ptr, "conn_id", &tcp_conn_id);
				op_ici_attr_get (transport_ici_ptr, "status",  &tcp_conn_status);
				
				/* Get the bgp connection details with the transport connection ID.		*/
				bgp_conn_info_ptr = (BgpT_Conn_Info*) bgp_connection_info_from_conn_id_get (tcp_conn_id);
				
				if (bgp_conn_info_ptr == OPC_NIL)
					{
					/* If a link or node goes down, we might continue to get TCP		*/
					/* Until TCP is properly fixed, just ignore them.					*/
					/*bgp_fatal_error ("In Open Confirm. Unable to map the tcp conn id to a bgp conn process");*/
					}
				else
				    {
					/* Invoke the connection.*/
				
					ev_ptr->event = OPEN_CONFIRM;
						printf("**Matched Connection Id..Calling connection confirm : %d event code\n", ev_ptr->event);
					//op_ici_print(transport_ici_ptr);
					if (op_pro_invoke (bgp_conn_info_ptr->bgp_connection_prohandle, ev_ptr) == OPC_COMPCODE_FAILURE)
						bgp_fatal_error("Unable to invoke child process for event code 2");
					}
					
				/* Also destroy the ICI from the TCP layer.							*/
				op_ici_destroy (transport_ici_ptr);
				}
				FSM_PROFILE_SECTION_OUT (state4_enter_exec)

			/** state (OPEN_CNFRM) exit executives **/
			FSM_STATE_EXIT_FORCED (4, "OPEN_CNFRM", "wban_tcp_server_trail_child [OPEN_CNFRM exit execs]")


			/** state (OPEN_CNFRM) transition processing **/
			FSM_TRANSIT_FORCE (5, state5_enter_exec, ;, "default", "", "OPEN_CNFRM", "idle", "tr_102", "wban_tcp_server_trail_child [OPEN_CNFRM -> idle : default / ]")
				/*---------------------------------------------------------*/



			/** state (idle) enter executives **/
			FSM_STATE_ENTER_UNFORCED (5, "idle", state5_enter_exec, "wban_tcp_server_trail_child [idle enter execs]")

			/** blocking after enter executives of unforced state. **/
			FSM_EXIT (11,"wban_tcp_server_trail_child")


			/** state (idle) exit executives **/
			FSM_STATE_EXIT_UNFORCED (5, "idle", "wban_tcp_server_trail_child [idle exit execs]")
				FSM_PROFILE_SECTION_IN ("wban_tcp_server_trail_child [idle exit execs]", state5_exit_exec)
				{
				/*	Determine the Interrupt Type and Interrupt Code.	*/
				/*	This is used to determine state transitions and		*/
				/*	process model logic.								*/
				intrpt_type = op_intrpt_type ();
				intrpt_code = op_intrpt_code ();
				
				if (intrpt_type == OPC_INTRPT_STRM)
					{
					/* TCP can send multiple BGP packets in a single interrupt. The		*/
					/* number of packets sent is indicated in the ICI.					*/
					transport_ici_ptr = op_intrpt_ici ();
				
					op_ici_attr_get_int32 (transport_ici_ptr, "packet count", &num_pkts);
					printf("****** Packets count at server : %d\n", num_pkts);
					}
				
				}
				FSM_PROFILE_SECTION_OUT (state5_exit_exec)


			/** state (idle) transition processing **/
			FSM_PROFILE_SECTION_IN ("wban_tcp_server_trail_child [idle trans conditions]", state5_trans_conds)
			FSM_INIT_COND (PKT_RECEIVE)
			FSM_TEST_COND (CONN_RELEASE)
			FSM_TEST_COND (TCP_INTRPT)
			FSM_TEST_COND (TCP_OPEN_IND)
			FSM_DFLT_COND
			FSM_TEST_LOGIC ("idle")
			FSM_PROFILE_SECTION_OUT (state5_trans_conds)

			FSM_TRANSIT_SWITCH
				{
				FSM_CASE_TRANSIT (0, 2, state2_enter_exec, ;, "PKT_RECEIVE", "", "idle", "RECEIVE", "tr_70", "wban_tcp_server_trail_child [idle -> RECEIVE : PKT_RECEIVE / ]")
				FSM_CASE_TRANSIT (1, 3, state3_enter_exec, ;, "CONN_RELEASE", "", "idle", "RELEASE", "tr_30", "wban_tcp_server_trail_child [idle -> RELEASE : CONN_RELEASE / ]")
				FSM_CASE_TRANSIT (2, 4, state4_enter_exec, ;, "TCP_INTRPT", "", "idle", "OPEN_CNFRM", "tr_101", "wban_tcp_server_trail_child [idle -> OPEN_CNFRM : TCP_INTRPT / ]")
				FSM_CASE_TRANSIT (3, 6, state6_enter_exec, ;, "TCP_OPEN_IND", "", "idle", "OPEN_IND", "tr_104", "wban_tcp_server_trail_child [idle -> OPEN_IND : TCP_OPEN_IND / ]")
				FSM_CASE_TRANSIT (4, 5, state5_enter_exec, ;, "default", "", "idle", "idle", "tr_124", "wban_tcp_server_trail_child [idle -> idle : default / ]")
				}
				/*---------------------------------------------------------*/



			/** state (OPEN_IND) enter executives **/
			FSM_STATE_ENTER_FORCED (6, "OPEN_IND", state6_enter_exec, "wban_tcp_server_trail_child [OPEN_IND enter execs]")
				FSM_PROFILE_SECTION_IN ("wban_tcp_server_trail_child [OPEN_IND enter execs]", state6_enter_exec)
				{
				/** Handles an indication from the TCP layer about a peer that is	**/
				/** attempting to establish connection with this BGP process. On	**/
				/** receipt of an OPEN Indication from a peer BGP process the local	**/
				/** system has to verify if it should accept the request or deny it	**/
				
				printf("SErver got open indication from client \n********");
				/* Obtain the ICI accompanying the interrupt.	*/
				tcp_open_ind_ici_ptr = op_intrpt_ici ();
				
				
				/* The remote address that made the connection request will be matched 	*/
				/* with the remote addresses that are entered in the list of allowed	*/
				/* IP addresses. The request will be granted if an address matches the 	*/
				/* requestors IP address.												*/
				if (op_ici_attr_get (tcp_open_ind_ici_ptr, "rem addr", &remote_addr_ptr) == OPC_COMPCODE_FAILURE ||
					op_ici_attr_get (tcp_open_ind_ici_ptr, "conn id",  &tcp_conn_id) == OPC_COMPCODE_FAILURE)
					{
					bgp_fatal_error ("In Open Indication. Unable to get remote address from ICI");
					
					}
				else
					{
					remote_addr = inet_address_copy (*remote_addr_ptr);
					
					inet_address_print(temp_addr_str, remote_addr);
					
					printf("Connect id : %d \t\t client address : %s\n", tcp_conn_id, temp_addr_str);
					
					/* Scan through the connections list and find out if there exists a	*/
					/* connection that has the given remote addr as its neighbor addr.	*/
					//bgp_conn_info_ptr = bgp_connection_info_from_conn_id_get (tcp_conn_id);
					bgp_conn_info_ptr = bgp_connection_info_from_conn_id_get (tcp_conn_id);
					printf("Connect id obtained in OPEN_IND: %d\n", tcp_conn_id);
					
					if (bgp_conn_info_ptr == OPC_NIL)
				    	{
						printf("Pointer is NIL \n");
						/* Open up a new connection with this connection ID.        */
							bgp_conn_info_ptr = bgp_ptc_mem_create (remote_addr, tcp_app_handle);
						
							
							/* Fill in the connection ID as we have this information.	*/
							bgp_conn_info_ptr->tcp_connection_id = tcp_conn_id;
						
							/* Set the flag to indicate that this connection was 		*/
							/* initiated by the neighbor.								*/
							//bgp_conn_info_ptr->locally_initiated = OPC_FALSE;
						
							/* Create and invoke the new connection.                   	*/
							ev_ptr->event = OPEN_IND;
							printf("OPEN ID indicator : %d\n", ev_ptr->event);
							bgp_conn_info_ptr->bgp_connection_prohandle = op_pro_create ("wban_tcp_server_trail", bgp_conn_info_ptr);
							op_pro_invoke (bgp_conn_info_ptr->bgp_connection_prohandle, ev_ptr);
							
							printf("Indicated OPEN_IND to child : %d\n", ev_ptr->event );
						
							/* Insert the new connection into the list.                	*/
							op_prg_list_insert (bgp_connections_list_ptr, bgp_conn_info_ptr, OPC_LISTPOS_TAIL);
						
							/* Schedule an procedure interrupt for the next passive 	*/
							/* transport connection.									*/
							op_intrpt_schedule_call (op_sim_time (), 0, server_passive_transport_conn_open, OPC_NIL);
							
							/* Indicate that the call can be accepted by TCP.			*/
							op_ici_attr_set (tcp_open_ind_ici_ptr, "accept status", TCPC_IND_CONNXN_ACCEPT);
							}
						else
							{
							/* Remote source not present in our neighbor list. This	*/
							/* is not allowed. Reject the connection.				*/
							
								/* Create and invoke the new connection.                   	*/
							
							printf("Pointer is not NIL \n");
							//ev_ptr->event = OPEN_IND;
							//printf("OPEN ID indicator : %d\n", OPEN_IND);
				
							//op_pro_invoke (bgp_conn_info_ptr->bgp_connection_prohandle, ev_ptr);
							
							//printf("Indicated OPEN_IND to child : %d\n", bgp_conn_info_ptr->tcp_connection_id);
							//op_ici_attr_set (tcp_open_ind_ici_ptr, "accept status", TCPC_IND_CONNXN_REJECT);
							
							/* Print out a log message indicating that such 		*/
							/* connections are not supported in real world and in	*/
							/* OPNET.												*/
							//bgp_unmatched_connection_request_received_warn (bgp_my_node_objid, remote_addr);
							}
						}
							
				    	
				}
				FSM_PROFILE_SECTION_OUT (state6_enter_exec)

			/** state (OPEN_IND) exit executives **/
			FSM_STATE_EXIT_FORCED (6, "OPEN_IND", "wban_tcp_server_trail_child [OPEN_IND exit execs]")


			/** state (OPEN_IND) transition processing **/
			FSM_TRANSIT_FORCE (5, state5_enter_exec, ;, "default", "", "OPEN_IND", "idle", "tr_103", "wban_tcp_server_trail_child [OPEN_IND -> idle : default / ]")
				/*---------------------------------------------------------*/



			}


		FSM_EXIT (0,"wban_tcp_server_trail_child")
		}
	catch (...)
		{
		Vos_Error_Print (VOSC_ERROR_ABORT,
			(const char *)VOSC_NIL,
			"Unhandled C++ exception in process model (wban_tcp_server_trail_child)",
			(const char *)VOSC_NIL, (const char *)VOSC_NIL);
		}
	}




void
wban_tcp_server_trail_child_state::_op_wban_tcp_server_trail_child_diag (OP_SIM_CONTEXT_ARG_OPT)
	{
	/* No Diagnostic Block */
	}

void
wban_tcp_server_trail_child_state::operator delete (void* ptr)
	{
	FIN (wban_tcp_server_trail_child_state::operator delete (ptr));
	Vos_Poolmem_Dealloc (ptr);
	FOUT
	}

wban_tcp_server_trail_child_state::~wban_tcp_server_trail_child_state (void)
	{

	FIN (wban_tcp_server_trail_child_state::~wban_tcp_server_trail_child_state ())


	/* No Termination Block */


	FOUT
	}


#undef FIN_PREAMBLE_DEC
#undef FIN_PREAMBLE_CODE

#define FIN_PREAMBLE_DEC
#define FIN_PREAMBLE_CODE

void *
wban_tcp_server_trail_child_state::operator new (size_t)
#if defined (VOSD_NEW_BAD_ALLOC)
		throw (VOSD_BAD_ALLOC)
#endif
	{
	void * new_ptr;

	FIN_MT (wban_tcp_server_trail_child_state::operator new ());

	new_ptr = Vos_Alloc_Object (wban_tcp_server_trail_child_state::obtype);
#if defined (VOSD_NEW_BAD_ALLOC)
	if (new_ptr == VOSC_NIL) throw VOSD_BAD_ALLOC();
#endif
	FRET (new_ptr)
	}

/* State constructor initializes FSM handling */
/* by setting the initial state to the first */
/* block of code to enter. */

wban_tcp_server_trail_child_state::wban_tcp_server_trail_child_state (void) :
		_op_current_block (0)
	{
#if defined (OPD_ALLOW_ODB)
		_op_current_state = "wban_tcp_server_trail_child [INIT enter execs]";
#endif
	}

VosT_Obtype
_op_wban_tcp_server_trail_child_init (int * init_block_ptr)
	{
	FIN_MT (_op_wban_tcp_server_trail_child_init (init_block_ptr))

	wban_tcp_server_trail_child_state::obtype = Vos_Define_Object_Prstate ("proc state vars (wban_tcp_server_trail_child)",
		sizeof (wban_tcp_server_trail_child_state));
	*init_block_ptr = 0;

	FRET (wban_tcp_server_trail_child_state::obtype)
	}

VosT_Address
_op_wban_tcp_server_trail_child_alloc (VosT_Obtype, int)
	{
#if !defined (VOSD_NO_FIN)
	int _op_block_origin = 0;
#endif
	wban_tcp_server_trail_child_state * ptr;
	FIN_MT (_op_wban_tcp_server_trail_child_alloc ())

	/* New instance will have FSM handling initialized */
#if defined (VOSD_NEW_BAD_ALLOC)
	try {
		ptr = new wban_tcp_server_trail_child_state;
	} catch (const VOSD_BAD_ALLOC &) {
		ptr = VOSC_NIL;
	}
#else
	ptr = new wban_tcp_server_trail_child_state;
#endif
	FRET ((VosT_Address)ptr)
	}



void
_op_wban_tcp_server_trail_child_svar (void * gen_ptr, const char * var_name, void ** var_p_ptr)
	{
	wban_tcp_server_trail_child_state		*prs_ptr;

	FIN_MT (_op_wban_tcp_server_trail_child_svar (gen_ptr, var_name, var_p_ptr))

	if (var_name == OPC_NIL)
		{
		*var_p_ptr = (void *)OPC_NIL;
		FOUT
		}
	prs_ptr = (wban_tcp_server_trail_child_state *)gen_ptr;

	if (strcmp ("my_id" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->my_id);
		FOUT
		}
	if (strcmp ("local_port" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->local_port);
		FOUT
		}
	if (strcmp ("remote_port" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->remote_port);
		FOUT
		}
	if (strcmp ("remote_inet_ip_addr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->remote_inet_ip_addr);
		FOUT
		}
	if (strcmp ("tcp_app_handle" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->tcp_app_handle);
		FOUT
		}
	if (strcmp ("connect_id" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->connect_id);
		FOUT
		}
	if (strcmp ("inet_address" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->inet_address);
		FOUT
		}
	if (strcmp ("conn_options" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->conn_options);
		FOUT
		}
	if (strcmp ("local_inet_ip_addr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->local_inet_ip_addr);
		FOUT
		}
	if (strcmp ("command_ici_ptr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->command_ici_ptr);
		FOUT
		}
	if (strcmp ("tcp_open_ind_ici_ptr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->tcp_open_ind_ici_ptr);
		FOUT
		}
	if (strcmp ("pFile" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->pFile);
		FOUT
		}
	if (strcmp ("stream_count" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->stream_count);
		FOUT
		}
	if (strcmp ("child_count" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->child_count);
		FOUT
		}
	if (strcmp ("child_proc" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->child_proc);
		FOUT
		}
	if (strcmp ("event" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->event);
		FOUT
		}
	if (strcmp ("bgp_connections_list_ptr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->bgp_connections_list_ptr);
		FOUT
		}
	if (strcmp ("bgp_error_str" , var_name) == 0)
		{
		*var_p_ptr = (void *) (prs_ptr->bgp_error_str);
		FOUT
		}
	if (strcmp ("ev_ptr" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->ev_ptr);
		FOUT
		}
	if (strcmp ("next_avail_peer_id" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->next_avail_peer_id);
		FOUT
		}
	if (strcmp ("num_pkts" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->num_pkts);
		FOUT
		}
	if (strcmp ("parent_id" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->parent_id);
		FOUT
		}
	if (strcmp ("conn_id" , var_name) == 0)
		{
		*var_p_ptr = (void *) (&prs_ptr->conn_id);
		FOUT
		}
	*var_p_ptr = (void *)OPC_NIL;

	FOUT
	}

